# @package _global_
exp_dir: '/media/E132-Projekte/Projects/2025_FOMO/finetuning_datasets/fomo-task3/results/'
data_dir: '/media/E132-Projekte/Projects/2025_FOMO/finetuning_datasets/fomo-task3/preprocessed_data/'

trainer:
  enable_progress_bar: False
  callbacks:
    progressbar: ~
