# @package _global_
exp_dir: '/media/E132-Projekte/Projects/2025_MartinezMora_SSLBrain/results/Dataset006_MRAAneurysmClassification'
data_dir: '/media/E132-Projekte/Projects/2025_MartinezMora_SSLBrain/preprocessed_data/Dataset006_MRAAneurysmClassification'
